### ISSUE TITLE
Bulk Import is not working

### ISSUE THREAD

**Issue by hiren101** [ugurkocde/IntuneOffboarding#4]
Bulk Import csv file to new V2 version for offloading is not working.

**Comment by nhasian** [comment]
I would like to be able to bulk remove devices from Autopilot using a CSV file. Where can I find test V2 of the application to test?

**Comment by ugurkocde** [comment]
Working on this and will release it in v3 ASAP.

**Comment by hiren101** [comment]
do you know when it will be released.
Hiren Shah 

    On Monday, March 25, 2024 at 07:22:04 AM EDT, Ugur Koc ***@***.***> wrote:  
 
 


Working on this and will release it in v3 ASAP.

**Comment by ugurkocde** [comment]
@hiren101 

Announcement is this week and release next week.
