### ISSUE TITLE
Feature Request : Add the ability to invoke commands (AutoPilot Reset, Wipe)

### ISSUE THREAD

**Issue by memile123** [ugurkocde/IntuneOffboarding#6]
Hello - Great tool, thank you. Any discussions or thoughts on expanding the functionalities during the offboarding process? It would be great if we could pass various device actions during the offboarding or before the offboarding. I'd be happy to add to this as well via pull request.

**Comment by ugurkocde** [comment]
Hello @memile123,

thanks for the request. This is a good idea but was not sure if people would missclick on wipe etc. and reset their devices by mistake. I think that we should approach this by creating a second script that has those features. I am thinking about something like Intune Offboarding "Advanced".

Besides these topics I have limited time. I would appreciate all pull requests that I will check before merging it.

What do you think?

Best regards
Ugur

**Comment by memile123** [comment]
@ugurkocde Apologies on the late reply here but that sounds great. I or others that see this need might be able to jump in and help.

**Comment by ugurkocde** [comment]
This will be a feature of v3. Need to rewrite the code base to make them work. Releasing it ASAP.
