### ISSUE TITLE
Cannot search if the serial number has spaces in it

### ISSUE THREAD

**Issue by dancing-groot** [ugurkocde/IntuneOffboarding#8]
Hi,

I know this is an edge case, mostly confined to testing purposes...
When using VMware virtual machines with Intune, the serial number looks like this:
VMware-12 3e 45 e9 95 fa 07 d3-30 2d 78 ad f8 06 d7 89

Because of the spaces, searching by serial number does not work.
Equally, when searching by device name, the Autopilot entry is not found.

**Comment by ugurkocde** [comment]
Hi,

i was not even aware of such edge cases with serial numbers that have spaces in it 😆 

I have finished a new version (release is next week) of this Tool that will also handle those cases.

Best regards
Ugur
